// src/app/core/errors/error-context.map.ts

export const errorContextMap: Record<string, string> = {
  // LOGIN
  INVALID_LOGIN: 'LOGIN.ERROR.BACKEND',
  TOO_MANY_FAILED_ATTEMPTS: 'LOGIN.ERROR.BACKEND',
  LOGIN_ATTEMPT_SAVE_FAILED: 'LOGIN.ERROR.BACKEND',
  LOGIN_FINALIZATION_FAILED: 'LOGIN.ERROR.BACKEND',

  // LOGOUT
  REFRESH_TOKEN_REQUIRED: 'LOGIN.ERROR.BACKEND',
  REFRESH_TOKEN_INVALID: 'LOGIN.ERROR.BACKEND',
  LOGOUT_FAILED: 'LOGIN.ERROR.BACKEND',

  // === SHARED COMMON BACKEND ERRORS ===
  EMAIL_ALREADY_USED: 'SHARED.ERROR.BACKEND',
  INVALID_EMAIL: 'SHARED.ERROR.BACKEND',
  INTERNAL_SERVER_ERROR: 'SHARED.ERROR.BACKEND',
  USER_NOT_FOUND: 'SHARED.ERROR.BACKEND',
  EMAIL_SENDING_FAILED: 'SHARED.ERROR.BACKEND',
  TOO_MANY_OTP_RESENDS: 'SHARED.ERROR.BACKEND',
  ACTUAL_PASSWORD_INVALID:'SHARED.ERROR.BACKEND',

  // === EMAIL CONFIRMATION ===
  EMAIL_CONFIRMATION_FAILED: 'CONFIRMEMAIL.ERROR.BACKEND',
  EMAIL_CONFIRMATION_INVALID_TOKEN: 'CONFIRMEMAIL.ERROR.BACKEND',
  EMAIL_ALREADY_CONFIRMED: 'CONFIRMEMAIL.ERROR.BACKEND',
  EMAIL_CONFIRMATION_TOO_EARLY: 'CONFIRMEMAIL.ERROR.BACKEND',
  EMAIL_CONFIRMATION_NOT_FOUND: 'CONFIRMEMAIL.ERROR.BACKEND',
  EMAIL_CONFIRMATION_TOKEN_EXPIRED: 'CONFIRMEMAIL.ERROR.BACKEND',
  OTP_TOO_MANY_ATTEMPTS:"CONFIRMEMAIL.ERROR.BACKEND",

  // RESETPASSWORD
  PASSWORD_RESET_TOKEN_INVALID: 'RESETPASSWORD.ERROR.BACKEND',
  PASSWORD_RESET_TOKEN_EXPIRED: 'RESETPASSWORD.ERROR.BACKEND',
  PASSWORD_RESET_TOKEN_USED: 'RESETPASSWORD.ERROR.BACKEND',
  PASSWORD_RESET_FAILED: 'RESETPASSWORD.ERROR.BACKEND',
  PASSWORD_RESET_ALREADY_REQUESTED: 'RESETPASSWORD.ERROR.BACKEND',
  PASSWORD_RESET_SAME_AS_OLD: 'RESETPASSWORD.ERROR.BACKEND',
  TOO_MANY_TOKEN_REQUESTS:'RESETPASSWORD.ERROR.BACKEND',




  // === INVITATION COLLEAGUE ===
  INVITER_NOT_ADMIN: 'INVITE.ERROR.BACKEND',
  INVITER_NOT_LINKED_TO_ENTITY: 'INVITE.ERROR.BACKEND',
  ROLE_NOT_VALID_FOR_ENTITY_TYPE: 'INVITE.ERROR.BACKEND',
  INVITATION_CREATION_FAILED: 'INVITE.ERROR.BACKEND',

  // === INVITATION COMPANY ===
  INVALID_COMPANY_INPUT: 'INVITE.ERROR.BACKEND',
  COMPANY_NAME_ALREADY_USED: 'INVITE.ERROR.BACKEND',
  COMPANY_CREATION_FAILED: 'INVITE.ERROR.BACKEND',

  // === INVITATION INSTITUTION ===
  INVALID_INSTITUTION_INPUT: 'INVITE.ERROR.BACKEND',
  INSTITUTION_NAME_ALREADY_USED: 'INVITE.ERROR.BACKEND',
  INSTITUTION_TYPE_NOT_FOUND: 'INVITE.ERROR.BACKEND',
  INSTITUTION_CREATION_FAILED: 'INVITE.ERROR.BACKEND',

  // === ENTITIES ===
  ENTITY_CREATION_FAILED: 'INVITE.ERROR.BACKEND',
  ENTITY_NAME_MISSING: 'INVITE.ERROR.BACKEND',
  ENTITY_TYPE_NOT_FOUND: 'INVITE.ERROR.BACKEND',
  ADMIN_ROLE_NOT_FOUND: 'INVITE.ERROR.BACKEND',

  // === REGISTER FROM INVITE ===
  INVITATION_INVALID: 'REGISTERFROMINVITE.ERROR.BACKEND',
  INVITATION_DETAILS_MISSING: 'REGISTERFROMINVITE.ERROR.BACKEND',
  USER_ALREADY_EXISTS: 'REGISTERFROMINVITE.ERROR.BACKEND',
  REGISTRATION_FAILED: 'REGISTERFROMINVITE.ERROR.BACKEND',
  ENTITY_TYPE_INVALID: 'REGISTERFROMINVITE.ERROR.BACKEND',
  ENTITY_TYPE_UNSUPPORTED: 'REGISTERFROMINVITE.ERROR.BACKEND',

  // Account
  RATE_LIMIT_EXCEEDED :"ACCOUNT.ERROR.BACKEND",

  // Ajout des valeurs des codes non mappés avec le contexte ERROR.BACKEND.VALIDATIONS
  REFRESH_TOKEN_LOCK_TIMEOUT: 'ERROR.BACKEND.VALIDATIONS',
  REFRESH_TOKEN_ALREADY_USED: 'ERROR.BACKEND.VALIDATIONS',
  REFRESH_TOKEN_ALREADY_EXISTS: 'ERROR.BACKEND.VALIDATIONS',
  NO_LEGAL_CONSENTS_PROVIDED: 'ERROR.BACKEND.VALIDATIONS',
  LEGAL_DOCUMENT_NOT_FOUND: 'ERROR.BACKEND.VALIDATIONS',
  OTP_NOT_REQUIRED_FOR_THIS_TOKEN_TYPE: 'ERROR.BACKEND.VALIDATIONS',
  TOKEN_NOT_AVAILABLE: 'ERROR.BACKEND.VALIDATIONS',
  TOKEN_NOT_FOUND: 'ERROR.BACKEND.VALIDATIONS',
  MISSING_CONFIRMATION_TOKEN_OR_OTP: 'ERROR.BACKEND.VALIDATIONS',
  OTP_INVALID: 'ERROR.BACKEND.VALIDATIONS',
  TOO_SOON_FOR_NEW_TOKEN: 'ERROR.BACKEND.VALIDATIONS',
  AUTH_USER_NULL: 'ERROR.BACKEND.VALIDATIONS',
  AUTH_MISSING_EMAIL: 'ERROR.BACKEND.VALIDATIONS',
  AUTH_TOKEN_GENERATION_FAILED: 'ERROR.BACKEND.VALIDATIONS',
  TOKEN_INVALID: 'ERROR.BACKEND.VALIDATIONS',
  AUTH_UNEXPECTED: 'ERROR.BACKEND.VALIDATIONS',
  TOKEN_ALREADY_USED: 'ERROR.BACKEND.VALIDATIONS',
  TOKEN_REVOKED: 'ERROR.BACKEND.VALIDATIONS',
  TOKEN_EXPIRED: 'ERROR.BACKEND.VALIDATIONS',
  TOKEN_TYPE_NOT_FOUND: 'ERROR.BACKEND.VALIDATIONS',
  INVALID_ADMIN_ROLE: 'ERROR.BACKEND.VALIDATIONS',
  REFRESH_TOKEN_INVALID_OR_EXPIRED: 'ERROR.BACKEND.VALIDATIONS',
  REFRESH_TOKEN_PROCESS_FAILED: 'ERROR.BACKEND.VALIDATIONS',
  INSTITUTION_DTO_NULL: 'ERROR.BACKEND.VALIDATIONS',
  INSTITUTION_TYPE_ID_INVALID: 'ERROR.BACKEND.VALIDATIONS',
  COMPANY_DTO_NULL: 'ERROR.BACKEND.VALIDATIONS',
  COMPANY_NUMBER_REQUIRED: 'ERROR.BACKEND.VALIDATIONS',
  COMPANY_NUMBER_INVALID_FORMAT: 'ERROR.BACKEND.VALIDATIONS',
  COMPANY_NUMBER_INVALID_DIGITS: 'ERROR.BACKEND.VALIDATIONS',
  COMPANY_NUMBER_INVALID: 'ERROR.BACKEND.VALIDATIONS',
  INVALID_NAME: 'ERROR.BACKEND.VALIDATIONS',
  INVALID_EMAIL_FORMAT: 'ERROR.BACKEND.VALIDATIONS',
  SESSION_EVENT_NOT_FOUND: 'ERROR.BACKEND.VALIDATIONS',
  NO_SESSION_TO_REVOCK: 'ERROR.BACKEND.VALIDATIONS',
  PASSWORD_INVALID: 'ERROR.BACKEND.VALIDATIONS',
  PASSWORD_UPDATE_FAILED: 'ERROR.BACKEND.VALIDATIONS',
  EMAIL_UNCHANGED: 'ERROR.BACKEND.VALIDATIONS',
  EMAIL_UPDATE_FAILED: 'ERROR.BACKEND.VALIDATIONS',
  NAMES_UNCHANGED: 'ERROR.BACKEND.VALIDATIONS',
  NAME_UPDATE_FAILED: 'ERROR.BACKEND.VALIDATIONS',
  INVALID_NAME_FIELDS: 'ERROR.BACKEND.VALIDATIONS',
  NEW_PASSWORD_INVALID: 'ERROR.BACKEND.VALIDATIONS',
  INVALID_NEW_EMAIL: 'ERROR.BACKEND.VALIDATIONS',
  INVITATION_DETAILS_MISMATCH: 'ERROR.BACKEND.VALIDATIONS',
  USER_CREATION_FAILED: 'ERROR.BACKEND.VALIDATIONS',
  COLLEAGUE_REGISTRATION_FAILED: 'ERROR.BACKEND.VALIDATIONS',
  USER_NOT_FOUND_AFTER_ENTITY_CREATION: 'ERROR.BACKEND.VALIDATIONS',
  USER_REGISTRATION_FAILED: 'ERROR.BACKEND.VALIDATIONS',
  ROLE_NOT_FOUND: 'ERROR.BACKEND.VALIDATIONS',
  PUBLIC_ENTITY_TYPE_NOT_FOUND: 'ERROR.BACKEND.VALIDATIONS',
  UNSUPPORTED_PUBLIC_ROLE: 'ERROR.BACKEND.VALIDATIONS',

};
