import { Injectable } from '@angular/core';
import { SearchStrategy } from './search-strategy.interface';
import { Observable, of } from 'rxjs';
import { delay } from 'rxjs/operators';
import { InternshipResult } from '../../../models/search.models';

@Injectable({ providedIn: 'root' })
export class InternshipSearchStrategy implements SearchStrategy<InternshipResult> {
  type = 'internships';

  constructor() {}

  search(query: any): Observable<InternshipResult[]> {
    const fakeResults: InternshipResult[] = [
      {
        id: 1,
        title: "Stage en architecture logicielle quantique",
        company: "NebulaSoft",
        location: "MégaCité Virtuelle",
        offerType: "Stage",
        contractType: "Stage",
        scheduleType: "Temps plein",
        salary: 720.0,
        currency: "CRD",
        startDate: "2025-09-01",
        isActive: true,
        description: "Participez à la conception de microservices instables dans un environnement simulé en 12 dimensions.",
        language: "fr",
        duration: 5,
        durationUnit: "mois",
        remotePossible: true,
        deadline: "2025-08-15",
      },
      {
        id: 2,
        title: "Stage en communication interplanétaire",
        company: "CosmoMedia",
        location: "Station Orbite-3",
        offerType: "Stage",
        contractType: "Stage",
        scheduleType: "Temps partiel",
        salary: 430.0,
        currency: "CRD",
        startDate: "2025-07-10",
        isActive: true,
        description: "Aidez à développer des campagnes publicitaires à destination des colonies lunaires. Aucune expérience spatiale requise.",
        language: "fr",
        duration: 4,
        durationUnit: "mois",
        remotePossible: false,
        deadline: "2025-06-30",
      },
      {
        id: 3,
        title: "Stage en design holographique",
        company: "PixelNova",
        location: "Secteur Graph-9",
        offerType: "Stage",
        contractType: "Stage",
        scheduleType: "Temps plein",
        salary: 560.0,
        currency: "CRD",
        startDate: "2025-08-01",
        isActive: true,
        description: "Concevez des interfaces holographiques pour tablettes spatiales. Bon sens esthétique intergalactique exigé.",
        language: "fr",
        duration: 6,
        durationUnit: "mois",
        remotePossible: true,
        deadline: "2025-07-10",
      },
      {
        id: 4,
        title: "Stage en gestion de données temporelles",
        company: "ChronoTech",
        location: "Ville du Temps, Continuum B",
        offerType: "Stage",
        contractType: "Stage",
        scheduleType: "Temps plein",
        salary: 510.0,
        currency: "CRD",
        startDate: "2025-09-15",
        isActive: true,
        description: "Manipulez des flux temporels et synchronisez les lignes du temps. Expérience en paradoxe temporel appréciée.",
        language: "fr",
        duration: 3,
        durationUnit: "mois",
        remotePossible: false,
        deadline: "2025-08-25",
      },
      {
        id: 5,
        title: "Stage en psychologie des intelligences artificielles",
        company: "MindBot Labs",
        location: "Dôme Cognitif, Sphère-12",
        offerType: "Stage",
        contractType: "Stage",
        scheduleType: "Temps partiel",
        salary: 490.0,
        currency: "CRD",
        startDate: "2025-07-20",
        isActive: true,
        description: "Étudiez le comportement émotionnel des IA et aidez-les à surmonter leur peur des boucles infinies.",
        language: "fr",
        duration: 4,
        durationUnit: "mois",
        remotePossible: true,
        deadline: "2025-07-01",
      },
      {
        id: 6,
        title: "Stage en biotechnologie alimentaire synthétique",
        company: "NutriCore X",
        location: "Cité BioSynth, Secteur Vert",
        offerType: "Stage",
        contractType: "Stage",
        scheduleType: "Temps plein",
        salary: 540.0,
        currency: "CRD",
        startDate: "2025-08-05",
        isActive: true,
        description: "Aidez à concevoir des hamburgers moléculaires et des jus de fruits en poudre. Goût garanti approximatif.",
        language: "fr",
        duration: 5,
        durationUnit: "mois",
        remotePossible: false,
        deadline: "2025-07-15",
      },
      {
        id: 7,
        title: "Stage en cybersécurité magique",
        company: "SpellShield Systems",
        location: "Tour 404, Royaume du Code",
        offerType: "Stage",
        contractType: "Stage",
        scheduleType: "Temps plein",
        salary: 580.0,
        currency: "CRD",
        startDate: "2025-09-10",
        isActive: true,
        description: "Protégez les portails numériques contre les sorts de phishing et les incantations malveillantes.",
        language: "fr",
        duration: 6,
        durationUnit: "mois",
        remotePossible: true,
        deadline: "2025-08-20",
      },
      {
        id: 8,
        title: "Stage en développement de jeux rétrofuturistes",
        company: "RetroVoid Studios",
        location: "Cité 8-Bit, Néo-Arcadia",
        offerType: "Stage",
        contractType: "Stage",
        scheduleType: "Temps plein",
        salary: 500.0,
        currency: "CRD",
        startDate: "2025-07-25",
        isActive: true,
        description: "Participez à la création de jeux rétro inspirés du futur des années 80. Passion du pixel exigée.",
        language: "fr",
        duration: 6,
        durationUnit: "mois",
        remotePossible: true,
        deadline: "2025-07-10",
      },
      {
        id: 9,
        title: "Stage en administration cosmique",
        company: "Bureau Galactique des Procédures",
        location: "Centre Administratif Zeta-9",
        offerType: "Stage",
        contractType: "Stage",
        scheduleType: "Temps partiel",
        salary: 420.0,
        currency: "CRD",
        startDate: "2025-08-15",
        isActive: true,
        description: "Classez des formulaires multidimensionnels et gérez les autorisations d’accès entre univers parallèles.",
        language: "fr",
        duration: 3,
        durationUnit: "mois",
        remotePossible: false,
        deadline: "2025-08-01",
      },
      {
        id: 10,
        title: "Stage en analyse des rêves numériques",
        company: "DreamWare Institute",
        location: "CyberLune",
        offerType: "Stage",
        contractType: "Stage",
        scheduleType: "Temps plein",
        salary: 610.0,
        currency: "CRD",
        startDate: "2025-09-05",
        isActive: true,
        description: "Analysez les rêves des intelligences artificielles et identifiez les bugs oniriques récurrents.",
        language: "fr",
        duration: 6,
        durationUnit: "mois",
        remotePossible: true,
        deadline: "2025-08-15",
      }
    ];


    const filtered = fakeResults.filter(internship =>
      (!query.keywords || internship.title.toLowerCase().includes(query.keywords.toLowerCase())) &&
      (!query.location || internship.location.toLowerCase().includes(query.location.toLowerCase()))
    );

    return of(filtered).pipe(delay(400));
  }
}
