import { Injectable } from '@angular/core';
import { SearchStrategy } from './search-strategy.interface';
import { Observable, of } from 'rxjs';
import { delay } from 'rxjs/operators';
import {StudyResult} from '../../../models/search.models';

@Injectable({ providedIn: 'root' })
export class StudySearchStrategy implements SearchStrategy<StudyResult> {
  type = 'studies';

  constructor() {}

  search(query: any): Observable<StudyResult[]> {
    const fakeResults: StudyResult[] = [
      {
        id: 1,
        title: "Bachelier en Sciences du Multivers",
        institution: "Université Interdimensionnelle de Nova Terra",
        location: "Cité des Portails",
        degreeType: "Bachelier",
        category: "Sciences",
        duration: 3,
        durationUnit: "années",
        credits: 180,
        cost: 950.0,
        currency: "CRD",
        language: "fr",
        deliveryMode: "Présentiel",
        isActive: true,
        description: "Programme explorant la physique quantique appliquée à la navigation entre univers parallèles. Laboratoires inclus.",
      },
      {
        id: 2,
        title: "Master en Gestion du Chaos Créatif",
        institution: "Institut Supérieur du Hasard Structuré",
        location: "Ville Fractale",
        degreeType: "Master",
        category: "Management",
        duration: 2,
        durationUnit: "années",
        credits: 120,
        cost: 1200.0,
        currency: "CRD",
        language: "fr",
        deliveryMode: "Hybride",
        isActive: true,
        description: "Formation avancée sur la prise de décision dans des environnements imprévisibles. Travaux pratiques sur le désordre organisé.",
      },
      {
        id: 3,
        title: "Licence en Communication Interespèces",
        institution: "Académie de Babel Universelle",
        location: "Capitale Polyglotte",
        degreeType: "Licence",
        category: "Communication",
        duration: 3,
        durationUnit: "années",
        credits: 180,
        cost: 650.0,
        currency: "CRD",
        language: "fr",
        deliveryMode: "Présentiel",
        isActive: true,
        description: "Étudiez les méthodes de communication entre espèces biologiques, robotiques et végétales. Inclut des échanges sur Mars.",
      },
      {
        id: 4,
        title: "Bachelier en Programmation Onirique",
        institution: "Université du Sommeil Numérique",
        location: "CyberLune",
        degreeType: "Bachelier",
        category: "Informatique",
        duration: 3,
        durationUnit: "années",
        credits: 180,
        cost: 850.0,
        currency: "CRD",
        language: "fr",
        deliveryMode: "Hybride",
        isActive: true,
        description: "Apprenez à coder dans les rêves artificiels. Les étudiants expérimenteront le débogage subconscient et la logique paradoxale.",
      },
      {
        id: 5,
        title: "DUT en Gestion Émotionnelle des Robots",
        institution: "Institut Technologique Sentientia",
        location: "Mécapole",
        degreeType: "DUT",
        category: "Robotique",
        duration: 2,
        durationUnit: "années",
        credits: 120,
        cost: 720.0,
        currency: "CRD",
        language: "fr",
        deliveryMode: "Présentiel",
        isActive: true,
        description: "Formation axée sur la maintenance émotionnelle et la communication empathique entre humains et IA sensibles.",
      },
      {
        id: 6,
        title: "Master en Philosophie Algorithmique",
        institution: "Université Post-Humaine d’ÉtherCity",
        location: "ÉtherCity",
        degreeType: "Master",
        category: "Philosophie",
        duration: 2,
        durationUnit: "années",
        credits: 120,
        cost: 1050.0,
        currency: "CRD",
        language: "fr",
        deliveryMode: "Hybride",
        isActive: true,
        description: "Analyse des fondements éthiques des algorithmes autonomes et des systèmes décisionnels conscients.",
      },
      {
        id: 7,
        title: "Bachelier en Ingénierie du Temps",
        institution: "École Supérieure ChronoTech",
        location: "Ville du Temps",
        degreeType: "Bachelier",
        category: "Ingénierie",
        duration: 3,
        durationUnit: "années",
        credits: 180,
        cost: 950.0,
        currency: "CRD",
        language: "fr",
        deliveryMode: "Présentiel",
        isActive: true,
        description: "Étude de la conception de dispositifs temporels et d’horloges dimensionnelles. Projets pratiques en chronodynamique appliquée.",
      },
      {
        id: 8,
        title: "Master en Écologie Galactique",
        institution: "Université de Biosphère Spatiale",
        location: "Station Orbitale Alpha",
        degreeType: "Master",
        category: "Sciences",
        duration: 2,
        durationUnit: "années",
        credits: 120,
        cost: 980.0,
        currency: "CRD",
        language: "fr",
        deliveryMode: "Présentiel",
        isActive: true,
        description: "Programme sur la préservation des écosystèmes planétaires et la gestion des biosphères artificielles.",
      },
      {
        id: 9,
        title: "Licence en Psychologie des Intelligences Artificielles",
        institution: "Institut NeuroData",
        location: "Cité Synaptique",
        degreeType: "Licence",
        category: "Psychologie",
        duration: 3,
        durationUnit: "années",
        credits: 180,
        cost: 890.0,
        currency: "CRD",
        language: "fr",
        deliveryMode: "Présentiel",
        isActive: true,
        description: "Explorez la cognition numérique et les émotions simulées des systèmes artificiels.",
      },
      {
        id: 10,
        title: "Bachelier en Architecture des Mondes Virtuels",
        institution: "Académie des Concepteurs Holo",
        location: "Néo-Arcadia",
        degreeType: "Bachelier",
        category: "Architecture",
        duration: 3,
        durationUnit: "années",
        credits: 180,
        cost: 880.0,
        currency: "CRD",
        language: "fr",
        deliveryMode: "Hybride",
        isActive: true,
        description: "Créez des environnements immersifs pour réalités virtuelles et univers simulés. Fusion entre art et code.",
      }
    ];


    const filtered = fakeResults.filter(study =>
      (!query.keywords || study.title.toLowerCase().includes(query.keywords.toLowerCase())) &&
      (!query.location || study.location.toLowerCase().includes(query.location.toLowerCase()))
    );

    return of(filtered).pipe(delay(350));
  }
}
